version: '3'
# Services -> containerlari tanimlar
services:

   # MariaDB Service
   mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      networks:
         - app-network
      env_file:
         - .env
      restart: always

   # Nginx Service
   nginx:
      container_name: nginx
      build: ./requirements/nginx
      ports:
         - "443:443" #bilgisayarın 443 portu -> container 443 portuna yönlendir.
      networks:
         - app-network
      env_file:
         - .env
      depends_on:
         - wordpress
      restart: always

   wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      networks:
         - app-network
      env_file:
         - .env
      depends_on:
         - mariadb
      restart: always


# Container'lar arasindaki ag baglantilarini tanimlar.
networks:
   app-network:
      driver: bridge
