version: '3.8'

# Container'lar arasindaki ag baglantilarini tanimlar.
networks:
   app-network:
      name: app-network
      driver: bridge

# Services -> containerlari tanimlar
services:

   # MariaDB Service
   mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      env_file:
         - .env
      volumes:
         -'mariadb:/var/lib/mysql'
      networks:
         - app-network
      depends_on:
         - wordpress
      restart: always

   # wordpress Service
   wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      env_file:
         - .env
      depends_on:
         - mariadb
      volumes:
         - wordpress:/var/www/html
      networks:
         - app-network
      restart: always

   # Nginx Service
   nginx:
      container_name: nginx
      build: ./requirements/nginx
      #image: nginx
      ports:
      - "443:443" #bilgisayarın 443 portu -> container 443 portuna yönlendir. 
      depends_on:
         - wordpress
      volumes:
         - wordpress:/var/www/html
      networks:
         - app-network
      restart: always

# Volumes -> containerlar icin veri kaynaklari
volumes:
   wordpress:
      driver: local
      name: wordpress
      driver_opts:
         type: bridge
         device: /home/data/wordpress
         o: bind
   mariadb:
      driver: local
      name: mariadb
      driver_opts:
         type: bridge
         device: /home/data/mysql
         o: bind